### ISSUE TITLE
How to trigger Alex to say some thing based on data sent form ESP32?

### ISSUE THREAD

**Issue by ahmedwahdan** [matwerber1/aws-alexa-smart-home-demo#12]
How to trigger Alex to say some thing based on data sent form ESP32?
Like "Motion was detected" or make it makes an alarm sound

**Comment by matwerber1** [comment]
I apologize for the delay. 

At the time I made this project a couple years ago, there was no native way to send a notification to the Alexa service (and by proxy, an Alexa-enabled device like an Amazon Echo). 

The good news is that, since then, the Alexa team has launched the [Proactive Events API](https://developer.amazon.com/en-US/docs/alexa/smapi/proactive-events-api.html) which will provide this functionality with certain restrictions. 

The restrictions are that this API will only allow you to send messages that fit one of the [pre-defined "event schemas"](https://developer.amazon.com/en-US/docs/alexa/smapi/proactive-events-api.html#understand-events-and-schemas) from the Alexa team. [This looks like it might be a good blog to review](https://medium.com/swlh/get-started-with-amazon-alexa-skills-proactive-events-api-5b082bcb282c). 

If your event doesn't fit the schema for this API, my understanding is there are no other Alexa-supported methods available at this time, but please confirm with your own research.

In addition to the Proactive Events API, Alexa has launched many other new features, APIs, etc. - I don't know specifics... but just sharing because it's possible this project is out-of-date and there may be better approaches available.
